networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8000:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - dev
    
  backend:
    build:
      context: ./backend
    networks:
      - dev
  
  frontend:
    build:
      context: ./frontend
    networks:
      - dev
